
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew bash
brew cmake
brew colordiff
brew curl
brew dep
brew fish
brew fzf
brew gettext
brew ghq
brew git
brew go
brew goenv
brew hugo
brew jemalloc
brew jenv
brew jq
brew libevent
brew libssh2
brew libtermkey
brew libuv
brew libvterm
brew lsof
brew lua@5.1
brew luajit
brew mas
brew mercurial
brew msgpack
brew neovim --HEAD
brew node-build
brew nodenv
brew oniguruma
brew openssl
brew openssl@1.1
brew pcre2
brew pkg-config
brew pv
brew pyenv
brew python
brew rbenv
brew readline
brew reattach-to-user-namespace
brew rsync
brew ruby-build
brew rustup-init
brew sbt
brew tmux
brew trash
brew tree
brew unibilium
brew wget
brew xz
brew yarn --without-node

tap caskroom/cask
cask slack
cask atom
cask steam
cask teamviewer
cask visual-studio-code
cask adobe-air
cask spotify
cask vlc
cask skype
cask kap
cask appcleaner
cask karabiner-elements
cask intellij-idea
cask google-backup-and-sync
cask keybase
cask pritunl
cask transmission
cask iterm2
cask dropbox
cask unity
cask visual-studio
cask docker
cask vagrant
cask clipy
cask gimp
cask scratch
cask sublime-text
cask 1password
cask discord
cask goland
cask horndis
cask firefox
cask microsoft-office
cask google-chrome
cask google-japanese-ime
cask mattr-slate
cask ngrok
cask java
cask docker-toolbox

tap caskroom/fonts
cask font-source-han-code-jp
cask font-source-code-pro-for-powerline

tap caskroom/versions
cask firefoxdeveloperedition
cask java8

tap caskroom/versions

tap beeftornado/rmtree

tap go-delve/delve
brew delve

tap rcmdnk/file
brew brew-file

# Cask applications
cask Kitematic

# App Store applications
appstore 539883307 LINE (5.3.3)
appstore 1176895641 Spark (1.4.2)
appstore 557168941 Tweetbot (2.5.3)
appstore 497799835 Xcode (9.0)
