source ~/.zplug/init.zsh

# Proxy Setting
if [ -d ${HOME}/Dropbox ] ; then
     source ~/Dropbox/myCommands/setproxy
fi

autoload -Uz compinit chpwd_recent_dirs cdr add-zsh-hook
compinit add-zsh-hook chpwd chpwd_recent_dirs

zplug "zsh-users/zsh-history-substring-search"
zplug "plugins/git", from:oh-my-zsh, if:"(( $+commands[git] ))", nice:10
zplug "zsh-users/zsh-syntax-highlighting", nice:10
zplug "plugins/golang", from:oh-my-zsh
# zplug "themes/sorin", from:oh-my-zsh
zplug "mafredri/zsh-async"
zplug "sindresorhus/pure"
zplug "zsh-users/zsh-completions"
zplug "motemen/ghq", \
    from:gh-r, \
    as:command, \
    use:"*darwin*amd64*"
zplug "junegunn/fzf-bin", \
    from:gh-r, \
    as:command, \
    rename-to:fzf, \
    use:"*darwin*amd64*"
zplug "mollifier/anyframe"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi

fi

zplug load --verbose

# 履歴ファイルの保存先
export HISTFILE=${HOME}/.zsh_history

# メモリに保存される履歴の件数
export HISTSIZE=1000

# 履歴ファイルに保存される履歴の件数
export SAVEHIST=100000

# 重複を記録しない
setopt hist_ignore_dups

# 開始と終了を記録
setopt EXTENDED_HISTORY

# substring-search のキーバインド
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# anyframe のキーバインド
bindkey '^a' anyframe-widget-select-widget

bindkey '^xb' anyframe-widget-cdr
bindkey '^x^b' anyframe-widget-checkout-git-branch

bindkey '^xr' anyframe-widget-execute-history
bindkey '^x^r' anyframe-widget-execute-history

bindkey '^xi' anyframe-widget-put-history
bindkey '^x^i' anyframe-widget-put-history

bindkey '^xg' anyframe-widget-cd-ghq-repository
bindkey '^x^g' anyframe-widget-cd-ghq-repository

bindkey '^xk' anyframe-widget-kill
bindkey '^x^k' anyframe-widget-kill

bindkey '^xe' anyframe-widget-insert-git-branch
bindkey '^x^e' anyframe-widget-insert-git-branch

# completion
zstyle ':completion:*:default' menu select=2
zstyle ':completion:*' verbose yes
zstyle ':completion:*' completer _expand _complete _match _prefix _approximate _list _history
zstyle ':completion:*:options' description 'yes'
# グループ名に空文字列を指定すると，マッチ対象のタグ名がグループ名に使われる。
# したがって，すべての マッチ種別を別々に表示させたいなら以下のようにする
zstyle ':completion:*' group-name ''

# cdr
zstyle ':completion:*' recent-dirs-insert both
zstyle ':chpwd:*' recent-dirs-max 500
zstyle ':chpwd:*' recent-dirs-default true
zstyle ':chpwd:*' recent-dirs-file "$HOME/.cache/shell/chpwd-recent-dirs"
zstyle ':chpwd:*' recent-dirs-pushd true

# LS_COLORSを設定しておく
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
# ファイル補完候補に色を付ける
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

#cdを打ったら自動的にlsを打ってくれる関数
function cd(){
    builtin cd $@ && ls -G;
}

# zsh-completions 読み込み
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -U compinit; compinit

# Aliases
alias vim='nvim'
alias rm='trash'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias ls='ls -G'
alias af='anyframe-widget-select-widget'

# Pathes
export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.local/share
export LANG=ja_JP.UTF-8
if [ -d ${HOME}/.anyenv ] ; then
  export PATH="$HOME/.anyenv/bin:$PATH"
  eval "$(anyenv init -)"
fi
if builtin command -v npm > /dev/null; then
  export PATH=$PATH:`npm bin -g`
fi
export GOPATH=$HOME/go
export PGDATA=/usr/local/var/postgres
