source ~/.zplug/init.zsh

# Proxy Setting
if [ -d ${HOME}/Dropbox ] ; then
     source ~/Dropbox/myCommands/setproxy
fi

zplug "zsh-users/zsh-history-substring-search"
zplug "plugins/git", from:oh-my-zsh, if:"(( $+commands[git] ))", nice:10
zplug "zsh-users/zsh-syntax-highlighting", nice:10
# zplug "themes/sorin", from:oh-my-zsh
zplug "mafredri/zsh-async"
zplug "sindresorhus/pure"
zplug "zsh-users/zsh-completions"
zplug "motemen/ghq", \
    from:gh-r, \
    as:command, \
    use:"*darwin*amd64*"
zplug "junegunn/fzf-bin", \
    from:gh-r, \
    as:command, \
    rename-to:fzf, \
    use:"*darwin*amd64*"
zplug "mollifier/anyframe"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi

fi

zplug load --verbose

# 履歴ファイルの保存先
export HISTFILE=${HOME}/.zsh_history

# メモリに保存される履歴の件数
export HISTSIZE=1000

# 履歴ファイルに保存される履歴の件数
export SAVEHIST=100000

# 重複を記録しない
setopt hist_ignore_dups

# 開始と終了を記録
setopt EXTENDED_HISTORY

# substring-search のキーバインド
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# anyframe のキーバインド
bindkey '^a' anyframe-widget-select-widget

bindkey '^xb' anyframe-widget-cdr
bindkey '^x^b' anyframe-widget-checkout-git-branch

bindkey '^xr' anyframe-widget-execute-history
bindkey '^x^r' anyframe-widget-execute-history

bindkey '^xi' anyframe-widget-put-history
bindkey '^x^i' anyframe-widget-put-history

bindkey '^xg' anyframe-widget-cd-ghq-repository
bindkey '^x^g' anyframe-widget-cd-ghq-repository

bindkey '^xk' anyframe-widget-kill
bindkey '^x^k' anyframe-widget-kill

bindkey '^xe' anyframe-widget-insert-git-branch
bindkey '^x^e' anyframe-widget-insert-git-branch

# Aliases
alias vim='nvim'
alias rm='trash'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'

# Pathes
export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.local/share
export LANG=ja_JP.UTF-8
if [ -d ${HOME}/.anyenv ] ; then
  export PATH="$HOME/.anyenv/bin:$PATH"
  eval "$(anyenv init -)"
fi
if builtin command -v npm > /dev/null; then
  export PATH=$PATH:`npm bin -g`
fi

autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
